2024-06-04 18:08:34,692 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:08:34,693 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:08:34,693 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:08:40,444 - websockets.server - INFO - connection open
2024-06-04 18:08:40,446 - __main__ - INFO - Received: 1
2024-06-04 18:08:40,446 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:08:40,451 - websockets.server - INFO - connection closed
2024-06-04 18:08:45,882 - websockets.server - INFO - connection open
2024-06-04 18:08:45,886 - __main__ - INFO - Received: 2
2024-06-04 18:08:45,886 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:08:45,894 - websockets.server - INFO - connection closed
2024-06-04 18:09:16,551 - websockets.server - INFO - connection open
2024-06-04 18:09:16,553 - __main__ - INFO - Received: 1
2024-06-04 18:09:16,553 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:09:16,557 - websockets.server - INFO - connection closed
2024-06-04 18:09:19,556 - websockets.server - INFO - connection open
2024-06-04 18:09:19,560 - __main__ - INFO - Received: 2
2024-06-04 18:09:19,560 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:09:19,569 - websockets.server - INFO - connection closed
2024-06-04 18:09:22,654 - websockets.server - INFO - connection open
2024-06-04 18:09:22,656 - __main__ - INFO - Received: 1
2024-06-04 18:09:22,656 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:09:22,660 - websockets.server - INFO - connection closed
2024-06-04 18:10:56,781 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:10:56,782 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:10:56,782 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:11:20,358 - websockets.server - INFO - connection open
2024-06-04 18:11:20,360 - __main__ - INFO - Received: 2
2024-06-04 18:11:20,360 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:11:21,365 - websockets.server - INFO - connection closed
2024-06-04 18:11:23,560 - websockets.server - INFO - connection open
2024-06-04 18:11:23,561 - __main__ - INFO - Received: 1
2024-06-04 18:11:23,562 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:11:24,567 - websockets.server - INFO - connection closed
2024-06-04 18:12:47,356 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:12:47,357 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:12:47,357 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:12:51,965 - websockets.server - INFO - connection open
2024-06-04 18:12:51,967 - __main__ - INFO - Received: 1
2024-06-04 18:12:51,968 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:12:52,972 - websockets.server - INFO - connection closed
2024-06-04 18:12:54,567 - websockets.server - INFO - connection open
2024-06-04 18:12:54,569 - __main__ - INFO - Received: 2
2024-06-04 18:12:54,569 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:12:55,579 - websockets.server - INFO - connection closed
2024-06-04 18:12:59,969 - websockets.server - INFO - connection open
2024-06-04 18:12:59,971 - __main__ - INFO - Received: 2
2024-06-04 18:12:59,971 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:13:00,980 - websockets.server - INFO - connection closed
2024-06-04 18:13:06,171 - websockets.server - INFO - connection open
2024-06-04 18:13:06,173 - __main__ - INFO - Received: 2
2024-06-04 18:13:06,173 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:13:07,181 - websockets.server - INFO - connection closed
2024-06-04 18:13:26,274 - websockets.server - INFO - connection open
2024-06-04 18:13:26,276 - __main__ - INFO - Received: 1
2024-06-04 18:13:26,276 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:13:27,280 - websockets.server - INFO - connection closed
2024-06-04 18:13:28,477 - websockets.server - INFO - connection open
2024-06-04 18:13:28,479 - __main__ - INFO - Received: 2
2024-06-04 18:13:28,479 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:13:29,483 - websockets.server - INFO - connection closed
2024-06-04 18:14:42,548 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:14:42,548 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:14:42,549 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:14:48,084 - websockets.server - INFO - connection open
2024-06-04 18:14:48,086 - __main__ - INFO - Received: 1
2024-06-04 18:14:48,086 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:14:49,095 - websockets.server - INFO - connection closed
2024-06-04 18:14:50,483 - websockets.server - INFO - connection open
2024-06-04 18:14:50,485 - __main__ - INFO - Received: 2
2024-06-04 18:14:50,485 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:14:51,490 - websockets.server - INFO - connection closed
2024-06-04 19:25:37,833 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 19:25:37,833 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 19:25:37,833 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 19:26:05,341 - websockets.server - INFO - connection open
2024-06-04 19:26:05,342 - __main__ - INFO - Received: 1
2024-06-04 19:26:05,342 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 19:26:06,346 - websockets.server - INFO - connection closed
2024-06-04 19:26:08,339 - websockets.server - INFO - connection open
2024-06-04 19:26:08,341 - __main__ - INFO - Received: 2
2024-06-04 19:26:08,341 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 19:26:09,345 - websockets.server - INFO - connection closed
2024-06-04 21:37:23,470 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:37:23,471 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:37:23,471 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:37:36,776 - websockets.server - INFO - connection open
2024-06-04 21:37:36,781 - __main__ - INFO - Received: 6
2024-06-04 21:37:36,781 - __main__ - INFO - Inicia la clase
2024-06-04 21:37:36,798 - websockets.server - INFO - connection closed
2024-06-04 21:37:39,450 - websockets.server - INFO - connection open
2024-06-04 21:37:39,452 - __main__ - INFO - Received: 1
2024-06-04 21:37:39,452 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:37:40,456 - websockets.server - INFO - connection closed
2024-06-04 21:37:42,558 - websockets.server - INFO - connection open
2024-06-04 21:37:42,563 - __main__ - INFO - Received: 2
2024-06-04 21:37:42,563 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:37:43,572 - websockets.server - INFO - connection closed
2024-06-04 21:37:46,657 - websockets.server - INFO - connection open
2024-06-04 21:37:46,659 - __main__ - INFO - Received: 7
2024-06-04 21:37:46,659 - __main__ - INFO - Finaliza la clase
2024-06-04 21:37:46,661 - websockets.server - INFO - connection closed
2024-06-04 21:40:31,681 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:40:31,681 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:40:31,681 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:40:42,469 - websockets.server - INFO - connection open
2024-06-04 21:40:42,472 - __main__ - INFO - Received: 6
2024-06-04 21:40:42,472 - __main__ - INFO - Inicia la clase
2024-06-04 21:40:47,663 - websockets.server - INFO - connection open
2024-06-04 21:40:47,665 - __main__ - INFO - Received: 1
2024-06-04 21:40:47,665 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:40:53,364 - websockets.server - INFO - connection open
2024-06-04 21:40:53,366 - __main__ - INFO - Received: 2
2024-06-04 21:40:53,366 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:40:57,066 - websockets.server - INFO - connection open
2024-06-04 21:40:57,068 - __main__ - INFO - Received: 7
2024-06-04 21:40:57,068 - __main__ - INFO - Finaliza la clase
2024-06-04 21:40:57,073 - websockets.server - INFO - connection closed
2024-06-04 21:41:02,970 - websockets.server - INFO - connection open
2024-06-04 21:41:02,972 - __main__ - INFO - Received: 7
2024-06-04 21:41:02,972 - __main__ - INFO - Finaliza la clase
2024-06-04 21:41:02,977 - websockets.server - INFO - connection closed
2024-06-04 21:41:43,099 - websockets.server - INFO - connection closed
2024-06-04 21:41:43,099 - websockets.server - INFO - connection closed
2024-06-04 21:41:43,100 - websockets.server - INFO - connection closed
2024-06-04 21:41:57,087 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:41:57,087 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:41:57,088 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:42:03,274 - websockets.server - INFO - connection open
2024-06-04 21:42:03,276 - __main__ - INFO - Received: 6
2024-06-04 21:42:03,276 - __main__ - INFO - Inicia la clase
2024-06-04 21:42:05,383 - websockets.server - INFO - connection open
2024-06-04 21:42:05,385 - __main__ - INFO - Received: 1
2024-06-04 21:42:05,385 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:42:09,277 - websockets.server - INFO - connection open
2024-06-04 21:42:09,279 - __main__ - INFO - Received: 7
2024-06-04 21:42:09,279 - __main__ - INFO - Finaliza la clase
2024-06-04 21:42:09,282 - websockets.server - INFO - connection closed
2024-06-04 21:43:32,225 - websockets.server - INFO - connection closed
2024-06-04 21:43:32,225 - websockets.server - INFO - connection closed
2024-06-04 21:43:51,210 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:43:51,211 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:43:51,211 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:44:02,192 - websockets.server - INFO - connection open
2024-06-04 21:44:02,194 - __main__ - INFO - Received: 6
2024-06-04 21:44:02,195 - __main__ - INFO - Inicia la clase
2024-06-04 21:44:07,085 - websockets.server - INFO - connection open
2024-06-04 21:44:07,086 - __main__ - INFO - Received: 1
2024-06-04 21:44:07,087 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:44:09,987 - websockets.server - INFO - connection open
2024-06-04 21:44:09,989 - __main__ - INFO - Received: 2
2024-06-04 21:44:09,989 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:44:13,893 - websockets.server - INFO - connection open
2024-06-04 21:44:13,895 - __main__ - INFO - Received: 7
2024-06-04 21:44:13,896 - __main__ - INFO - Finaliza la clase
2024-06-04 21:44:13,900 - websockets.server - INFO - connection closed
2024-06-04 21:45:30,329 - websockets.server - INFO - connection closed
2024-06-04 21:45:30,329 - websockets.server - INFO - connection closed
2024-06-04 21:45:30,330 - websockets.server - INFO - connection closed
2024-06-04 21:46:51,256 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:46:51,257 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:46:51,257 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:47:02,705 - websockets.server - INFO - connection open
2024-06-04 21:47:02,707 - __main__ - INFO - Received: 6
2024-06-04 21:47:02,708 - __main__ - INFO - Inicia la clase
2024-06-04 21:47:07,597 - websockets.server - INFO - connection open
2024-06-04 21:47:07,599 - __main__ - INFO - Received: 1
2024-06-04 21:47:07,599 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:47:15,804 - websockets.server - INFO - connection open
2024-06-04 21:47:15,806 - __main__ - INFO - Received: 2
2024-06-04 21:47:15,806 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:47:19,605 - websockets.server - INFO - connection open
2024-06-04 21:47:19,607 - __main__ - INFO - Received: 7
2024-06-04 21:47:19,608 - __main__ - INFO - Finaliza la clase
2024-06-04 21:47:19,613 - websockets.server - INFO - connection closed
2024-06-04 21:47:25,803 - websockets.server - INFO - connection open
2024-06-04 21:47:25,805 - __main__ - INFO - Received: 6
2024-06-04 21:47:25,805 - __main__ - INFO - Inicia la clase
2024-06-04 21:47:30,506 - websockets.server - INFO - connection open
2024-06-04 21:47:30,508 - __main__ - INFO - Received: 7
2024-06-04 21:47:30,509 - __main__ - INFO - Finaliza la clase
2024-06-04 21:47:30,514 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,086 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,087 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,087 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,087 - websockets.server - INFO - connection closed
2024-06-04 21:49:29,375 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:49:29,375 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:49:29,375 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:49:36,609 - websockets.server - INFO - connection open
2024-06-04 21:49:36,610 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    while is_running:
          ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'is_running' where it is not associated with a value
2024-06-04 21:49:36,612 - websockets.server - INFO - connection closed
2024-06-04 21:49:51,324 - websockets.server - INFO - connection open
2024-06-04 21:49:51,324 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    while is_running:
          ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'is_running' where it is not associated with a value
2024-06-04 21:49:51,326 - websockets.server - INFO - connection closed
2024-06-04 21:50:15,925 - websockets.server - INFO - connection open
2024-06-04 21:50:15,926 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    while is_running:
          ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'is_running' where it is not associated with a value
2024-06-04 21:50:15,928 - websockets.server - INFO - connection closed
2024-06-04 21:51:32,664 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:51:32,664 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:51:32,664 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:51:41,628 - websockets.server - INFO - connection open
2024-06-04 21:51:41,631 - __main__ - INFO - Received: 6
2024-06-04 21:51:41,631 - __main__ - INFO - Inicia la clase
2024-06-04 21:51:41,638 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:51:41,641 - websockets.server - INFO - connection closed
2024-06-04 21:51:45,225 - websockets.server - INFO - connection open
2024-06-04 21:51:45,227 - __main__ - INFO - Received: 1
2024-06-04 21:51:45,227 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:51:46,231 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:51:46,233 - websockets.server - INFO - connection closed
2024-06-04 21:51:50,026 - websockets.server - INFO - connection open
2024-06-04 21:51:50,029 - __main__ - INFO - Received: 7
2024-06-04 21:51:50,029 - __main__ - INFO - Finaliza la clase
2024-06-04 21:51:50,034 - websockets.server - INFO - connection closed
2024-06-04 21:51:56,631 - websockets.server - INFO - connection open
2024-06-04 21:51:56,632 - __main__ - INFO - Received: 7
2024-06-04 21:51:56,632 - __main__ - INFO - Finaliza la clase
2024-06-04 21:51:56,636 - websockets.server - INFO - connection closed
2024-06-04 21:52:03,729 - websockets.server - INFO - connection open
2024-06-04 21:52:03,731 - __main__ - INFO - Received: 1
2024-06-04 21:52:03,731 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:52:04,737 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:52:04,739 - websockets.server - INFO - connection closed
2024-06-04 21:52:06,428 - websockets.server - INFO - connection open
2024-06-04 21:52:06,430 - __main__ - INFO - Received: 2
2024-06-04 21:52:06,430 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:52:07,434 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:52:07,436 - websockets.server - INFO - connection closed
2024-06-04 21:53:38,442 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:53:38,442 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:53:38,443 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:53:44,733 - websockets.server - INFO - connection open
2024-06-04 21:53:44,735 - __main__ - INFO - Recibido: 6
2024-06-04 21:53:44,735 - __main__ - INFO - Iniciando la clase
2024-06-04 21:53:44,742 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:44,746 - websockets.server - INFO - connection closed
2024-06-04 21:53:49,934 - websockets.server - INFO - connection open
2024-06-04 21:53:49,936 - __main__ - INFO - Recibido: 1
2024-06-04 21:53:49,936 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 21:53:50,941 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:50,942 - websockets.server - INFO - connection closed
2024-06-04 21:53:53,137 - websockets.server - INFO - connection open
2024-06-04 21:53:53,139 - __main__ - INFO - Recibido: 1
2024-06-04 21:53:53,139 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 21:53:54,143 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:54,145 - websockets.server - INFO - connection closed
2024-06-04 21:53:56,138 - websockets.server - INFO - connection open
2024-06-04 21:53:56,140 - __main__ - INFO - Recibido: 2
2024-06-04 21:53:56,140 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-04 21:53:57,144 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:57,145 - websockets.server - INFO - connection closed
2024-06-04 21:54:00,842 - websockets.server - INFO - connection open
2024-06-04 21:54:00,844 - __main__ - INFO - Recibido: 7
2024-06-04 21:54:00,844 - __main__ - INFO - Finalizando la clase
2024-06-04 21:54:00,847 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 47, in handle_client
    await websocket.send(response)
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2024-06-04 21:54:00,849 - websockets.server - INFO - connection closed
2024-06-04 22:17:25,071 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 22:17:25,071 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 22:17:25,071 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 22:17:38,372 - websockets.server - INFO - connection open
2024-06-04 22:17:38,373 - __main__ - INFO - Recibido: 1
2024-06-04 22:17:38,374 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 22:17:39,378 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 22:17:39,381 - websockets.server - INFO - connection closed
2024-06-04 22:17:41,381 - websockets.server - INFO - connection open
2024-06-04 22:17:41,382 - __main__ - INFO - Recibido: 2
2024-06-04 22:17:41,383 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-04 22:17:42,387 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 22:17:42,388 - websockets.server - INFO - connection closed
2024-06-04 22:17:44,974 - websockets.server - INFO - connection open
2024-06-04 22:17:44,976 - __main__ - INFO - Recibido: 1
2024-06-04 22:17:44,976 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 22:17:45,982 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 22:17:45,984 - websockets.server - INFO - connection closed
2024-06-05 17:21:55,311 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 17:21:55,312 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 17:21:55,312 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 17:22:07,912 - websockets.server - INFO - connection open
2024-06-05 17:22:07,914 - __main__ - INFO - Recibido: 1
2024-06-05 17:22:07,914 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 17:22:08,920 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 17:22:08,929 - websockets.server - INFO - connection closed
2024-06-05 17:22:10,803 - websockets.server - INFO - connection open
2024-06-05 17:22:10,805 - __main__ - INFO - Recibido: 2
2024-06-05 17:22:10,805 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-05 17:22:11,810 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 17:22:11,811 - websockets.server - INFO - connection closed
2024-06-05 17:22:14,002 - websockets.server - INFO - connection open
2024-06-05 17:22:14,004 - __main__ - INFO - Recibido: 1
2024-06-05 17:22:14,004 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 17:22:15,008 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 17:22:15,010 - websockets.server - INFO - connection closed
2024-06-05 19:34:46,198 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 19:34:46,198 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 19:34:46,198 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 19:38:10,896 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 19:38:10,897 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 19:38:10,897 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 19:40:42,218 - websockets.server - INFO - connection open
2024-06-05 19:40:42,220 - __main__ - INFO - Recibido: 6
2024-06-05 19:40:42,220 - __main__ - INFO - Iniciando la clase
2024-06-05 19:40:42,246 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:40:42,249 - websockets.server - INFO - connection closed
2024-06-05 19:40:50,413 - websockets.server - INFO - connection open
2024-06-05 19:40:50,415 - __main__ - INFO - Recibido: 6
2024-06-05 19:40:50,415 - __main__ - INFO - Iniciando la clase
2024-06-05 19:40:50,430 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:40:50,432 - websockets.server - INFO - connection closed
2024-06-05 19:43:33,816 - websockets.server - INFO - connection open
2024-06-05 19:43:33,818 - __main__ - INFO - Recibido: 6
2024-06-05 19:43:33,818 - __main__ - INFO - Iniciando la clase
2024-06-05 19:43:33,848 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:43:33,850 - websockets.server - INFO - connection closed
2024-06-05 19:46:01,732 - websockets.server - INFO - connection open
2024-06-05 19:46:01,735 - __main__ - INFO - Recibido: 6
2024-06-05 19:46:01,736 - __main__ - INFO - Iniciando la clase
2024-06-05 19:46:01,743 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 399, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7c928590>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5080): Max retries exceeded with url: /log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c928590>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 45, in handle_client
    requests.get(url, json=data)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5080): Max retries exceeded with url: /log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c928590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-05 19:46:01,768 - websockets.server - INFO - connection closed
2024-06-05 19:48:49,907 - websockets.server - INFO - connection open
2024-06-05 19:48:49,909 - __main__ - INFO - Recibido: 6
2024-06-05 19:48:49,909 - __main__ - INFO - Iniciando la clase
2024-06-05 19:48:49,940 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:48:49,941 - websockets.server - INFO - connection closed
2024-06-05 19:50:04,800 - websockets.server - INFO - connection open
2024-06-05 19:50:04,802 - __main__ - INFO - Recibido: 1
2024-06-05 19:50:04,802 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:50:05,806 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:50:05,807 - websockets.server - INFO - connection closed
2024-06-05 19:50:07,102 - websockets.server - INFO - connection open
2024-06-05 19:50:07,104 - __main__ - INFO - Recibido: 6
2024-06-05 19:50:07,104 - __main__ - INFO - Iniciando la clase
2024-06-05 19:50:07,121 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:50:07,123 - websockets.server - INFO - connection closed
2024-06-05 19:50:57,509 - websockets.server - INFO - connection open
2024-06-05 19:50:57,511 - __main__ - INFO - Recibido: 6
2024-06-05 19:50:57,511 - __main__ - INFO - Iniciando la clase
2024-06-05 19:50:57,526 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:50:57,528 - websockets.server - INFO - connection closed
2024-06-05 19:51:01,708 - websockets.server - INFO - connection open
2024-06-05 19:51:01,710 - __main__ - INFO - Recibido: 1
2024-06-05 19:51:01,710 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:51:02,714 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:51:02,716 - websockets.server - INFO - connection closed
2024-06-05 19:52:49,415 - websockets.server - INFO - connection open
2024-06-05 19:52:49,416 - __main__ - INFO - Recibido: 6
2024-06-05 19:52:49,416 - __main__ - INFO - Iniciando la clase
2024-06-05 19:52:49,431 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:52:49,433 - websockets.server - INFO - connection closed
2024-06-05 19:53:47,522 - websockets.server - INFO - connection open
2024-06-05 19:53:47,525 - __main__ - INFO - Recibido: 6
2024-06-05 19:53:47,526 - __main__ - INFO - Iniciando la clase
2024-06-05 19:53:47,586 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:53:47,589 - websockets.server - INFO - connection closed
2024-06-05 19:54:17,326 - websockets.server - INFO - connection open
2024-06-05 19:54:17,331 - __main__ - INFO - Recibido: 6
2024-06-05 19:54:17,331 - __main__ - INFO - Iniciando la clase
2024-06-05 19:54:17,397 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:54:17,400 - websockets.server - INFO - connection closed
2024-06-05 19:56:18,212 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 19:56:18,212 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 19:56:18,212 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 19:56:26,026 - websockets.server - INFO - connection open
2024-06-05 19:56:26,028 - __main__ - INFO - Recibido: 1
2024-06-05 19:56:26,028 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:56:27,033 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:56:27,036 - websockets.server - INFO - connection closed
2024-06-05 19:56:32,830 - websockets.server - INFO - connection open
2024-06-05 19:56:32,832 - __main__ - INFO - Recibido: 2
2024-06-05 19:56:32,832 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-05 19:56:33,836 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:56:33,838 - websockets.server - INFO - connection closed
2024-06-05 19:56:38,732 - websockets.server - INFO - connection open
2024-06-05 19:56:38,733 - __main__ - INFO - Recibido: 1
2024-06-05 19:56:38,734 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:56:39,738 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:56:39,739 - websockets.server - INFO - connection closed
2024-06-05 19:57:32,344 - websockets.server - INFO - connection open
2024-06-05 19:57:32,346 - __main__ - INFO - Recibido: 6
2024-06-05 19:57:32,347 - __main__ - INFO - Iniciando la clase
2024-06-05 19:57:32,387 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:57:32,390 - websockets.server - INFO - connection closed
2024-06-05 19:58:20,846 - websockets.server - INFO - connection open
2024-06-05 19:58:20,848 - __main__ - INFO - Recibido: 6
2024-06-05 19:58:20,848 - __main__ - INFO - Iniciando la clase
2024-06-05 19:58:20,877 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:58:20,879 - websockets.server - INFO - connection closed
2024-06-05 20:00:23,051 - websockets.server - INFO - connection open
2024-06-05 20:00:23,054 - __main__ - INFO - Recibido: 6
2024-06-05 20:00:23,054 - __main__ - INFO - Iniciando la clase
2024-06-05 20:00:23,083 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:00:23,084 - websockets.server - INFO - connection closed
2024-06-05 20:00:38,251 - websockets.server - INFO - connection open
2024-06-05 20:00:38,252 - __main__ - INFO - Recibido: 7
2024-06-05 20:00:38,253 - __main__ - INFO - Finalizando la clase
2024-06-05 20:00:38,256 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:00:38,258 - websockets.server - INFO - connection closed
2024-06-05 20:01:12,031 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 20:01:12,031 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 20:01:12,031 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 20:01:25,964 - websockets.server - INFO - connection open
2024-06-05 20:01:25,966 - __main__ - INFO - Recibido: 6
2024-06-05 20:01:25,966 - __main__ - INFO - Iniciando la clase
2024-06-05 20:01:26,000 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:01:26,003 - websockets.server - INFO - connection closed
2024-06-05 20:02:11,963 - websockets.server - INFO - connection open
2024-06-05 20:02:11,965 - __main__ - INFO - Recibido: 6
2024-06-05 20:02:11,965 - __main__ - INFO - Iniciando la clase
2024-06-05 20:02:11,981 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:02:11,983 - websockets.server - INFO - connection closed
2024-06-05 20:05:41,369 - websockets.server - INFO - connection open
2024-06-05 20:05:41,370 - __main__ - INFO - Recibido: 6
2024-06-05 20:05:41,370 - __main__ - INFO - Iniciando la clase
2024-06-05 20:05:41,394 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:05:41,396 - websockets.server - INFO - connection closed
2024-06-05 20:06:50,773 - websockets.server - INFO - connection open
2024-06-05 20:06:50,775 - __main__ - INFO - Recibido: 6
2024-06-05 20:06:50,775 - __main__ - INFO - Iniciando la clase
2024-06-05 20:06:50,797 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:06:50,799 - websockets.server - INFO - connection closed
2024-06-05 20:07:04,878 - websockets.server - INFO - connection open
2024-06-05 20:07:04,879 - __main__ - INFO - Recibido: 1
2024-06-05 20:07:04,879 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 20:07:05,883 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:07:05,885 - websockets.server - INFO - connection closed
2024-06-05 20:25:41,192 - websockets.server - INFO - connection open
2024-06-05 20:25:41,196 - __main__ - INFO - Recibido: 6
2024-06-05 20:25:41,196 - __main__ - INFO - Iniciando la clase
2024-06-05 20:25:41,285 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:25:41,286 - websockets.server - INFO - connection closed
2024-06-05 20:29:05,598 - websockets.server - INFO - connection open
2024-06-05 20:29:05,602 - __main__ - INFO - Recibido: 6
2024-06-05 20:29:05,602 - __main__ - INFO - Iniciando la clase
2024-06-05 20:29:05,665 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:29:05,669 - websockets.server - INFO - connection closed
2024-06-05 20:29:26,496 - websockets.server - INFO - connection open
2024-06-05 20:29:26,498 - __main__ - INFO - Recibido: 6
2024-06-05 20:29:26,498 - __main__ - INFO - Iniciando la clase
2024-06-05 20:29:26,524 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:29:26,525 - websockets.server - INFO - connection closed
2024-06-05 20:29:40,315 - websockets.server - INFO - connection open
2024-06-05 20:29:40,317 - __main__ - INFO - Recibido: 6
2024-06-05 20:29:40,317 - __main__ - INFO - Iniciando la clase
2024-06-05 20:29:40,339 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:29:40,340 - websockets.server - INFO - connection closed
2024-06-05 20:35:48,492 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 20:35:48,492 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 20:35:48,492 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 20:36:56,412 - websockets.server - INFO - connection open
2024-06-05 20:36:56,413 - __main__ - INFO - Recibido: 6
2024-06-05 20:36:56,414 - __main__ - INFO - Iniciando la clase
2024-06-05 20:36:56,440 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:36:56,444 - websockets.server - INFO - connection closed
2024-06-05 20:37:00,413 - websockets.server - INFO - connection open
2024-06-05 20:37:00,415 - __main__ - INFO - Recibido: 1
2024-06-05 20:37:00,415 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-05 20:37:00,435 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 20:37:01,439 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:01,441 - websockets.server - INFO - connection closed
2024-06-05 20:37:04,017 - websockets.server - INFO - connection open
2024-06-05 20:37:04,019 - __main__ - INFO - Recibido: 2
2024-06-05 20:37:04,019 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-05 20:37:04,033 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-05 20:37:05,037 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:05,038 - websockets.server - INFO - connection closed
2024-06-05 20:37:10,023 - websockets.server - INFO - connection open
2024-06-05 20:37:10,025 - __main__ - INFO - Recibido: 3
2024-06-05 20:37:10,025 - __main__ - INFO - Se ha iniciado la grabacion
2024-06-05 20:37:10,044 - __main__ - INFO - Ejecutando script para empezar grabación
2024-06-05 20:37:10,049 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:10,051 - websockets.server - INFO - connection closed
2024-06-05 20:37:14,025 - websockets.server - INFO - connection open
2024-06-05 20:37:14,029 - __main__ - INFO - Recibido: 4
2024-06-05 20:37:14,030 - __main__ - INFO - Se ha detenido la grabacion
2024-06-05 20:37:14,053 - __main__ - INFO - Deteniendo la grabación
2024-06-05 20:37:14,060 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:14,062 - websockets.server - INFO - connection closed
2024-06-05 20:37:16,821 - websockets.server - INFO - connection open
2024-06-05 20:37:16,823 - __main__ - INFO - Recibido: 5
2024-06-05 20:37:16,823 - __main__ - INFO - Se ha tomado una foto
2024-06-05 20:37:16,848 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:16,849 - websockets.server - INFO - connection closed
2024-06-05 20:37:21,823 - websockets.server - INFO - connection open
2024-06-05 20:37:21,825 - __main__ - INFO - Recibido: 7
2024-06-05 20:37:21,825 - __main__ - INFO - Termina la clase
2024-06-05 20:37:21,839 - __main__ - INFO - Finalizando la clase
2024-06-05 20:37:21,843 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:21,845 - websockets.server - INFO - connection closed
2024-06-05 20:37:26,231 - websockets.server - INFO - connection open
2024-06-05 20:37:26,235 - __main__ - INFO - Recibido: 1
2024-06-05 20:37:26,235 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-05 20:37:26,261 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 20:37:27,267 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:27,268 - websockets.server - INFO - connection closed
2024-06-06 17:37:10,798 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:37:10,799 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:37:10,800 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:37:13,626 - websockets.server - INFO - connection open
2024-06-06 17:37:13,628 - __main__ - INFO - Recibido: 6
2024-06-06 17:37:13,628 - __main__ - INFO - Iniciando la clase
2024-06-06 17:37:13,668 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:37:13,674 - websockets.server - INFO - connection closed
2024-06-06 17:37:19,118 - websockets.server - INFO - connection open
2024-06-06 17:37:19,120 - __main__ - INFO - Recibido: 1
2024-06-06 17:37:19,120 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:37:19,134 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:37:20,139 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:37:20,141 - websockets.server - INFO - connection closed
2024-06-06 17:37:25,623 - websockets.server - INFO - connection open
2024-06-06 17:37:25,625 - __main__ - INFO - Recibido: 5
2024-06-06 17:37:25,625 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:37:25,649 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 65, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:37:25,651 - websockets.server - INFO - connection closed
2024-06-06 17:37:47,233 - websockets.server - INFO - connection open
2024-06-06 17:37:47,235 - __main__ - INFO - Recibido: 6
2024-06-06 17:37:47,235 - __main__ - INFO - Iniciando la clase
2024-06-06 17:37:47,265 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:37:47,266 - websockets.server - INFO - connection closed
2024-06-06 17:37:51,929 - websockets.server - INFO - connection open
2024-06-06 17:37:51,933 - __main__ - INFO - Recibido: 5
2024-06-06 17:37:51,933 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:37:51,960 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 65, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:37:51,966 - websockets.server - INFO - connection closed
2024-06-06 17:38:06,638 - websockets.server - INFO - connection open
2024-06-06 17:38:06,640 - __main__ - INFO - Recibido: 1
2024-06-06 17:38:06,640 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:38:06,655 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:38:07,660 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:38:07,661 - websockets.server - INFO - connection closed
2024-06-06 17:38:20,535 - websockets.server - INFO - connection open
2024-06-06 17:38:20,536 - __main__ - INFO - Recibido: 1
2024-06-06 17:38:20,537 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:38:20,550 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:38:21,555 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:38:21,557 - websockets.server - INFO - connection closed
2024-06-06 17:38:27,335 - websockets.server - INFO - connection open
2024-06-06 17:38:27,337 - __main__ - INFO - Recibido: 2
2024-06-06 17:38:27,337 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-06 17:38:27,351 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-06 17:38:28,358 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:38:28,361 - websockets.server - INFO - connection closed
2024-06-06 17:38:33,538 - websockets.server - INFO - connection open
2024-06-06 17:38:33,539 - __main__ - INFO - Recibido: 1
2024-06-06 17:38:33,540 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:38:33,553 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:38:34,561 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:38:34,564 - websockets.server - INFO - connection closed
2024-06-06 17:38:37,441 - websockets.server - INFO - connection open
2024-06-06 17:38:37,443 - __main__ - INFO - Recibido: 5
2024-06-06 17:38:37,443 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:38:37,459 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 65, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:38:37,461 - websockets.server - INFO - connection closed
2024-06-06 17:41:17,332 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:41:17,332 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:41:17,333 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:41:24,056 - websockets.server - INFO - connection open
2024-06-06 17:41:24,058 - __main__ - INFO - Recibido: 1
2024-06-06 17:41:24,058 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:41:24,075 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:41:25,080 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:41:25,083 - websockets.server - INFO - connection closed
2024-06-06 17:41:29,349 - websockets.server - INFO - connection open
2024-06-06 17:41:29,351 - __main__ - INFO - Recibido: 1
2024-06-06 17:41:29,351 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:41:29,363 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:41:30,368 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:41:30,369 - websockets.server - INFO - connection closed
2024-06-06 17:41:41,854 - websockets.server - INFO - connection open
2024-06-06 17:41:41,856 - __main__ - INFO - Recibido: 5
2024-06-06 17:41:41,856 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:41:41,871 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:41:41,871 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 66, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:41:41,873 - websockets.server - INFO - connection closed
2024-06-06 17:44:56,451 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:44:56,451 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:44:56,452 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:45:46,351 - websockets.server - INFO - connection open
2024-06-06 17:45:46,355 - __main__ - INFO - Recibido: 1
2024-06-06 17:45:46,356 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:45:46,383 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:45:47,388 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:45:47,391 - websockets.server - INFO - connection closed
2024-06-06 17:45:51,626 - websockets.server - INFO - connection open
2024-06-06 17:45:51,628 - __main__ - INFO - Recibido: 1
2024-06-06 17:45:51,628 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:45:51,640 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:45:52,648 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:45:52,651 - websockets.server - INFO - connection closed
2024-06-06 17:46:01,830 - websockets.server - INFO - connection open
2024-06-06 17:46:01,832 - __main__ - INFO - Recibido: 5
2024-06-06 17:46:01,832 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:46:01,848 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 66, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:46:01,850 - websockets.server - INFO - connection closed
2024-06-06 17:46:55,494 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:46:55,494 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:46:55,494 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:46:58,667 - websockets.server - INFO - connection open
2024-06-06 17:46:58,670 - __main__ - INFO - Recibido: 5
2024-06-06 17:46:58,670 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:46:58,703 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:46:58,711 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:46:58,719 - websockets.server - INFO - connection closed
2024-06-06 17:47:09,240 - websockets.server - INFO - connection open
2024-06-06 17:47:09,242 - __main__ - INFO - Recibido: 2
2024-06-06 17:47:09,242 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-06 17:47:09,257 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-06 17:47:10,261 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:47:10,262 - websockets.server - INFO - connection closed
2024-06-06 17:47:11,641 - websockets.server - INFO - connection open
2024-06-06 17:47:11,643 - __main__ - INFO - Recibido: 1
2024-06-06 17:47:11,643 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 17:47:11,654 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 17:47:12,658 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:47:12,660 - websockets.server - INFO - connection closed
2024-06-06 17:48:35,164 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:48:35,165 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:48:35,165 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:48:54,945 - websockets.server - INFO - connection open
2024-06-06 17:48:54,947 - __main__ - INFO - Recibido: 5
2024-06-06 17:48:54,947 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:48:54,963 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:48:54,964 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 66, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:48:54,966 - websockets.server - INFO - connection closed
2024-06-06 17:49:08,855 - websockets.server - INFO - connection open
2024-06-06 17:49:08,857 - __main__ - INFO - Recibido: 6
2024-06-06 17:49:08,857 - __main__ - INFO - Iniciando la clase
2024-06-06 17:49:08,882 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:49:08,884 - websockets.server - INFO - connection closed
2024-06-06 17:49:12,448 - websockets.server - INFO - connection open
2024-06-06 17:49:12,450 - __main__ - INFO - Recibido: 5
2024-06-06 17:49:12,450 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:49:12,464 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:49:12,464 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 66, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:49:12,466 - websockets.server - INFO - connection closed
2024-06-06 17:53:55,599 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:53:55,600 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:53:55,600 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:53:59,667 - websockets.server - INFO - connection open
2024-06-06 17:53:59,669 - __main__ - INFO - Recibido: 6
2024-06-06 17:53:59,670 - __main__ - INFO - Iniciando la clase
2024-06-06 17:53:59,699 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:53:59,702 - websockets.server - INFO - connection closed
2024-06-06 17:54:02,761 - websockets.server - INFO - connection open
2024-06-06 17:54:02,762 - __main__ - INFO - Recibido: 5
2024-06-06 17:54:02,762 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:54:02,776 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:54:02,777 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 66, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:54:02,778 - websockets.server - INFO - connection closed
2024-06-06 17:54:32,150 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:54:32,150 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:54:32,150 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:55:05,285 - websockets.server - INFO - connection open
2024-06-06 17:55:05,287 - __main__ - INFO - Recibido: 6
2024-06-06 17:55:05,288 - __main__ - INFO - Iniciando la clase
2024-06-06 17:55:05,315 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:55:05,318 - websockets.server - INFO - connection closed
2024-06-06 17:55:08,878 - websockets.server - INFO - connection open
2024-06-06 17:55:08,880 - __main__ - INFO - Recibido: 6
2024-06-06 17:55:08,880 - __main__ - INFO - Iniciando la clase
2024-06-06 17:55:08,904 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:55:08,905 - websockets.server - INFO - connection closed
2024-06-06 17:55:15,886 - websockets.server - INFO - connection open
2024-06-06 17:55:15,890 - __main__ - INFO - Recibido: 5
2024-06-06 17:55:15,891 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:55:15,918 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:55:15,919 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 66, in handle_client
    captura_camara(ruta_recursos)
                   ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ruta_recursos' where it is not associated with a value
2024-06-06 17:55:15,922 - websockets.server - INFO - connection closed
2024-06-06 17:56:22,673 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:56:22,674 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:56:22,674 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:56:25,596 - websockets.server - INFO - connection open
2024-06-06 17:56:25,598 - __main__ - INFO - Recibido: 5
2024-06-06 17:56:25,599 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:56:25,616 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:56:28,498 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:56:28,501 - websockets.server - INFO - connection closed
2024-06-06 17:56:28,690 - websockets.server - INFO - connection open
2024-06-06 17:56:28,692 - __main__ - INFO - Recibido: 5
2024-06-06 17:56:28,692 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:56:28,708 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:56:31,338 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:56:31,339 - websockets.server - INFO - connection closed
2024-06-06 17:57:12,125 - websockets.server - INFO - connection open
2024-06-06 17:57:12,127 - __main__ - INFO - Recibido: 5
2024-06-06 17:57:12,127 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:57:12,141 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:57:15,005 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:57:15,007 - websockets.server - INFO - connection closed
2024-06-06 17:57:45,020 - websockets.server - INFO - connection open
2024-06-06 17:57:45,022 - __main__ - INFO - Recibido: 5
2024-06-06 17:57:45,022 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:57:45,036 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:57:47,903 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:57:47,904 - websockets.server - INFO - connection closed
2024-06-06 17:58:42,283 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 17:58:42,284 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 17:58:42,284 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 17:59:15,627 - websockets.server - INFO - connection open
2024-06-06 17:59:15,631 - __main__ - INFO - Recibido: 5
2024-06-06 17:59:15,632 - __main__ - INFO - Se ha tomado una foto
2024-06-06 17:59:15,664 - __main__ - INFO - se ha tomado una foto
2024-06-06 17:59:18,589 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 17:59:18,592 - websockets.server - INFO - connection closed
2024-06-06 18:05:07,186 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 18:05:07,186 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 18:05:07,186 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 18:05:37,798 - websockets.server - INFO - connection open
2024-06-06 18:05:37,800 - __main__ - INFO - Recibido: 6
2024-06-06 18:05:37,800 - __main__ - INFO - Iniciando la clase
2024-06-06 18:05:37,817 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 77, in handle_client
    ruta_recursos = f"/datos/{clase}"
                              ^^^^^
NameError: name 'clase' is not defined
2024-06-06 18:05:37,820 - websockets.server - INFO - connection closed
2024-06-06 18:05:51,832 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 18:05:51,832 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 18:05:51,832 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 18:05:57,922 - websockets.server - INFO - connection open
2024-06-06 18:05:57,926 - __main__ - INFO - Recibido: 6
2024-06-06 18:05:57,927 - __main__ - INFO - Iniciando la clase
2024-06-06 18:05:57,961 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 77, in handle_client
    ruta_recursos = f"/datos/{clase}"
                              ^^^^^
NameError: name 'clase' is not defined
2024-06-06 18:05:57,967 - websockets.server - INFO - connection closed
2024-06-06 18:06:04,722 - websockets.server - INFO - connection open
2024-06-06 18:06:04,727 - __main__ - INFO - Recibido: 5
2024-06-06 18:06:04,727 - __main__ - INFO - Se ha tomado una foto
2024-06-06 18:06:04,754 - __main__ - INFO - se ha tomado una foto
2024-06-06 18:06:04,754 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 65, in handle_client
    ruta=f"/datos/{clase}"
                   ^^^^^
NameError: name 'clase' is not defined
2024-06-06 18:06:04,758 - websockets.server - INFO - connection closed
2024-06-06 18:06:14,109 - websockets.server - INFO - connection open
2024-06-06 18:06:14,111 - __main__ - INFO - Recibido: 6
2024-06-06 18:06:14,111 - __main__ - INFO - Iniciando la clase
2024-06-06 18:06:14,125 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 77, in handle_client
    ruta_recursos = f"/datos/{clase}"
                              ^^^^^
NameError: name 'clase' is not defined
2024-06-06 18:06:14,127 - websockets.server - INFO - connection closed
2024-06-06 18:07:51,685 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 18:07:51,686 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 18:07:51,686 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-06 18:07:56,213 - websockets.server - INFO - connection open
2024-06-06 18:07:56,215 - __main__ - INFO - Recibido: 5
2024-06-06 18:07:56,215 - __main__ - INFO - Se ha tomado una foto
2024-06-06 18:07:56,238 - __main__ - INFO - se ha tomado una foto
2024-06-06 18:07:59,162 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 18:07:59,165 - websockets.server - INFO - connection closed
2024-06-06 18:10:35,594 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 18:10:35,594 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 18:10:35,594 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class ASO
2024-06-06 18:10:40,918 - websockets.server - INFO - connection open
2024-06-06 18:10:40,922 - __main__ - INFO - Recibido: 6
2024-06-06 18:10:40,922 - __main__ - INFO - Iniciando la clase
2024-06-06 18:10:40,946 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 18:10:40,950 - websockets.server - INFO - connection closed
2024-06-06 18:10:48,112 - websockets.server - INFO - connection open
2024-06-06 18:10:48,114 - __main__ - INFO - Recibido: 5
2024-06-06 18:10:48,114 - __main__ - INFO - Se ha tomado una foto
2024-06-06 18:10:48,128 - __main__ - INFO - se ha tomado una foto
2024-06-06 18:10:51,047 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 18:10:51,049 - websockets.server - INFO - connection closed
2024-06-06 18:23:05,764 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 18:23:05,764 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 18:23:05,764 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class SRI
2024-06-06 18:23:33,981 - websockets.server - INFO - connection open
2024-06-06 18:23:33,986 - __main__ - INFO - Recibido: 6
2024-06-06 18:23:33,986 - __main__ - INFO - Iniciando la clase
2024-06-06 18:23:34,028 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 18:23:34,036 - websockets.server - INFO - connection closed
2024-06-06 18:23:42,546 - websockets.server - INFO - connection open
2024-06-06 18:23:42,547 - __main__ - INFO - Recibido: 1
2024-06-06 18:23:42,547 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 18:23:42,565 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 18:23:43,570 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 18:23:43,571 - websockets.server - INFO - connection closed
2024-06-06 18:23:51,954 - websockets.server - INFO - connection open
2024-06-06 18:23:51,957 - __main__ - INFO - Recibido: 5
2024-06-06 18:23:51,958 - __main__ - INFO - Se ha tomado una foto
2024-06-06 18:23:51,984 - __main__ - INFO - se ha tomado una foto
2024-06-06 18:23:54,913 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 18:23:54,914 - websockets.server - INFO - connection closed
2024-06-06 19:11:04,997 - websockets.server - INFO - connection open
2024-06-06 19:11:04,999 - __main__ - INFO - Recibido: 6
2024-06-06 19:11:04,999 - __main__ - INFO - Iniciando la clase
2024-06-06 19:11:05,018 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 19:11:05,020 - websockets.server - INFO - connection closed
2024-06-06 19:11:09,290 - websockets.server - INFO - connection open
2024-06-06 19:11:09,292 - __main__ - INFO - Recibido: 1
2024-06-06 19:11:09,292 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 19:11:09,305 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 19:11:10,309 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 19:11:10,311 - websockets.server - INFO - connection closed
2024-06-06 19:11:12,293 - websockets.server - INFO - connection open
2024-06-06 19:11:12,294 - __main__ - INFO - Recibido: 2
2024-06-06 19:11:12,295 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-06 19:11:12,308 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-06 19:11:13,316 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 19:11:13,319 - websockets.server - INFO - connection closed
2024-06-06 19:11:16,096 - websockets.server - INFO - connection open
2024-06-06 19:11:16,097 - __main__ - INFO - Recibido: 7
2024-06-06 19:11:16,098 - __main__ - INFO - Termina la clase
2024-06-06 19:11:16,111 - __main__ - INFO - Finalizando la clase
2024-06-06 19:11:16,115 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 19:11:16,116 - websockets.server - INFO - connection closed
2024-06-06 19:11:24,197 - websockets.server - INFO - connection open
2024-06-06 19:11:24,199 - __main__ - INFO - Recibido: 7
2024-06-06 19:11:24,199 - __main__ - INFO - Termina la clase
2024-06-06 19:11:24,213 - __main__ - INFO - Finalizando la clase
2024-06-06 19:11:24,217 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 19:11:24,218 - websockets.server - INFO - connection closed
2024-06-06 19:12:27,928 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 19:12:27,928 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 19:12:27,928 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class SRI
2024-06-06 19:12:32,002 - websockets.server - INFO - connection open
2024-06-06 19:12:32,003 - __main__ - INFO - Recibido: 1
2024-06-06 19:12:32,004 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-06 19:12:32,020 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-06 19:12:33,024 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-06 19:12:33,028 - websockets.server - INFO - connection closed
2024-06-06 19:12:35,103 - websockets.server - INFO - connection open
2024-06-06 19:12:35,105 - __main__ - INFO - Recibido: 7
2024-06-06 19:12:35,105 - __main__ - INFO - Termina la clase
2024-06-06 19:12:35,119 - __main__ - INFO - Finalizando la clase
2024-06-06 19:12:35,119 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 96, in handle_client
    sys.exit()
    ^^^
NameError: name 'sys' is not defined
2024-06-06 19:12:35,121 - websockets.server - INFO - connection closed
2024-06-06 19:12:39,614 - websockets.server - INFO - connection open
2024-06-06 19:12:39,616 - __main__ - INFO - Recibido: 7
2024-06-06 19:12:39,616 - __main__ - INFO - Termina la clase
2024-06-06 19:12:39,630 - __main__ - INFO - Finalizando la clase
2024-06-06 19:12:39,630 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 96, in handle_client
    sys.exit()
    ^^^
NameError: name 'sys' is not defined
2024-06-06 19:12:39,632 - websockets.server - INFO - connection closed
2024-06-06 19:12:47,817 - websockets.server - INFO - connection open
2024-06-06 19:12:47,820 - __main__ - INFO - Recibido: 7
2024-06-06 19:12:47,820 - __main__ - INFO - Termina la clase
2024-06-06 19:12:47,834 - __main__ - INFO - Finalizando la clase
2024-06-06 19:12:47,834 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 96, in handle_client
    sys.exit()
    ^^^
NameError: name 'sys' is not defined
2024-06-06 19:12:47,836 - websockets.server - INFO - connection closed
2024-06-06 19:13:34,110 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 19:13:34,111 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 19:13:34,111 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class SRI
2024-06-06 19:13:36,620 - websockets.server - INFO - connection open
2024-06-06 19:13:36,622 - __main__ - INFO - Recibido: 7
2024-06-06 19:13:36,622 - __main__ - INFO - Termina la clase
2024-06-06 19:13:36,639 - __main__ - INFO - Finalizando la clase
2024-06-06 19:13:36,640 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 96, in handle_client
    sys.exit(1)
    ^^^
NameError: name 'sys' is not defined
2024-06-06 19:13:36,642 - websockets.server - INFO - connection closed
2024-06-06 19:13:41,422 - websockets.server - INFO - connection open
2024-06-06 19:13:41,423 - __main__ - INFO - Recibido: 7
2024-06-06 19:13:41,424 - __main__ - INFO - Termina la clase
2024-06-06 19:13:41,437 - __main__ - INFO - Finalizando la clase
2024-06-06 19:13:41,438 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 96, in handle_client
    sys.exit(1)
    ^^^
NameError: name 'sys' is not defined
2024-06-06 19:13:41,439 - websockets.server - INFO - connection closed
2024-06-06 19:14:29,898 - websockets.server - INFO - server listening on [::1]:8766
2024-06-06 19:14:29,899 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-06 19:14:29,899 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class SRI
2024-06-06 19:14:45,727 - websockets.server - INFO - connection open
2024-06-06 19:14:45,730 - __main__ - INFO - Recibido: 7
2024-06-06 19:14:45,730 - __main__ - INFO - Termina la clase
2024-06-06 19:14:45,746 - __main__ - INFO - Finalizando la clase
2024-06-06 19:14:45,747 - websockets.server - INFO - connection closed
2024-06-06 19:14:45,779 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<WebSocketServerProtocol.handler() done, defined at /usr/lib/python3/dist-packages/websockets/legacy/server.py:153> exception=SystemExit(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 96, in handle_client
    quit()
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: None
2024-06-07 18:27:32,369 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-07 18:27:32,370 - websockets.server - INFO - server listening on [::1]:8766
2024-06-07 18:27:32,370 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class ASO!
2024-06-07 18:27:35,573 - websockets.server - INFO - connection open
2024-06-07 18:27:35,577 - __main__ - INFO - Recibido: 1
2024-06-07 18:27:35,578 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-07 18:27:35,622 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-07 18:27:36,631 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:27:36,644 - websockets.server - INFO - connection closed
2024-06-07 18:27:37,954 - websockets.server - INFO - connection open
2024-06-07 18:27:37,958 - __main__ - INFO - Recibido: 2
2024-06-07 18:27:37,958 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-07 18:27:37,985 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-07 18:27:38,993 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:27:38,997 - websockets.server - INFO - connection closed
2024-06-07 18:27:48,761 - websockets.server - INFO - connection open
2024-06-07 18:27:48,764 - __main__ - INFO - Recibido: 1
2024-06-07 18:27:48,765 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-07 18:27:48,790 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-07 18:27:49,794 - websockets.server - INFO - connection closed
2024-06-07 18:31:04,950 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-07 18:31:04,951 - websockets.server - INFO - server listening on [::1]:8766
2024-06-07 18:31:04,951 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class ASO!
2024-06-07 18:31:05,814 - websockets.server - INFO - connection open
2024-06-07 18:31:05,816 - __main__ - INFO - Recibido: 2
2024-06-07 18:31:05,816 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-07 18:31:05,833 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-07 18:31:06,837 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:31:06,840 - websockets.server - INFO - connection closed
2024-06-07 18:31:09,311 - websockets.server - INFO - connection open
2024-06-07 18:31:09,315 - __main__ - INFO - Recibido: 2
2024-06-07 18:31:09,315 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-07 18:31:09,341 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-07 18:31:10,349 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:31:10,353 - websockets.server - INFO - connection closed
2024-06-07 18:31:11,514 - websockets.server - INFO - connection open
2024-06-07 18:31:11,517 - __main__ - INFO - Recibido: 1
2024-06-07 18:31:11,517 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-07 18:31:11,541 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-07 18:31:12,548 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 25, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:31:12,551 - websockets.server - INFO - connection closed
2024-06-07 18:46:50,920 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-07 18:46:50,921 - websockets.server - INFO - server listening on [::1]:8766
2024-06-07 18:46:50,921 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class ASO11
2024-06-07 18:47:26,656 - websockets.server - INFO - connection open
2024-06-07 18:47:26,658 - __main__ - INFO - Recibido: 6
2024-06-07 18:47:26,659 - __main__ - INFO - Iniciando la clase
2024-06-07 18:47:26,680 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:47:26,683 - websockets.server - INFO - connection closed
2024-06-07 18:47:31,156 - websockets.server - INFO - connection open
2024-06-07 18:47:31,159 - __main__ - INFO - Recibido: 5
2024-06-07 18:47:31,160 - __main__ - INFO - Se ha tomado una foto
2024-06-07 18:47:31,190 - __main__ - INFO - se ha tomado una foto
2024-06-07 18:47:34,462 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:47:34,465 - websockets.server - INFO - connection closed
2024-06-07 18:49:51,829 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-07 18:49:51,830 - websockets.server - INFO - server listening on [::1]:8766
2024-06-07 18:49:51,830 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class ASO11
2024-06-07 18:49:51,862 - websockets.server - INFO - connection open
2024-06-07 18:49:51,864 - __main__ - INFO - Recibido: 6
2024-06-07 18:49:51,864 - __main__ - INFO - Iniciando la clase
2024-06-07 18:49:51,884 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:49:51,887 - websockets.server - INFO - connection closed
2024-06-07 18:50:00,070 - websockets.server - INFO - connection open
2024-06-07 18:50:00,073 - __main__ - INFO - Recibido: 5
2024-06-07 18:50:00,074 - __main__ - INFO - Se ha tomado una foto
2024-06-07 18:50:00,100 - __main__ - INFO - se ha tomado una foto
2024-06-07 18:50:03,077 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:50:03,080 - websockets.server - INFO - connection closed
2024-06-07 18:50:10,172 - websockets.server - INFO - connection open
2024-06-07 18:50:10,176 - __main__ - INFO - Recibido: 3
2024-06-07 18:50:10,176 - __main__ - INFO - Se ha iniciado la grabacion
2024-06-07 18:50:10,207 - __main__ - INFO - Ejecutando script para empezar grabación
2024-06-07 18:50:10,214 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:50:10,218 - websockets.server - INFO - connection closed
2024-06-07 18:50:58,474 - websockets.server - INFO - connection open
2024-06-07 18:50:58,476 - __main__ - INFO - Recibido: 5
2024-06-07 18:50:58,476 - __main__ - INFO - Se ha tomado una foto
2024-06-07 18:50:58,491 - __main__ - INFO - se ha tomado una foto
2024-06-07 18:51:01,394 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:51:01,395 - websockets.server - INFO - connection closed
2024-06-07 18:53:16,194 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-07 18:53:16,194 - websockets.server - INFO - server listening on [::1]:8766
2024-06-07 18:53:16,194 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class ASO111
2024-06-07 18:53:44,128 - websockets.server - INFO - connection open
2024-06-07 18:53:44,132 - __main__ - INFO - Recibido: 6
2024-06-07 18:53:44,132 - __main__ - INFO - Iniciando la clase
2024-06-07 18:53:44,160 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:53:44,164 - websockets.server - INFO - connection closed
2024-06-07 18:53:50,990 - websockets.server - INFO - connection open
2024-06-07 18:53:50,994 - __main__ - INFO - Recibido: 8
2024-06-07 18:53:50,994 - __main__ - INFO - Tomando foto a una pizarra
2024-06-07 18:53:51,022 - __main__ - INFO - Se ha tomado una foto a una pizarra
2024-06-07 18:54:39,918 - websockets.server - INFO - connection closed
2024-06-07 18:54:39,991 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-9' coro=<WebSocketServerProtocol.handler() done, defined at /usr/lib/python3/dist-packages/websockets/legacy/server.py:153> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/opt/scripts/socket_cliente.py", line 125, in <module>
    asyncio.run(main(args.clase))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 107, in handle_client
    captura_pizarra(f"/datos/{clase}")
  File "/opt/scripts/take_pizarra.py", line 35, in captura_pizarra
    while time.time() - start_time < 15:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
2024-06-07 18:55:05,924 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-07 18:55:05,925 - websockets.server - INFO - server listening on [::1]:8766
2024-06-07 18:55:05,925 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class ASO1111
2024-06-07 18:55:09,825 - websockets.server - INFO - connection open
2024-06-07 18:55:09,829 - __main__ - INFO - Recibido: 6
2024-06-07 18:55:09,830 - __main__ - INFO - Iniciando la clase
2024-06-07 18:55:09,869 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:55:09,877 - websockets.server - INFO - connection closed
2024-06-07 18:55:13,516 - websockets.server - INFO - connection open
2024-06-07 18:55:13,519 - __main__ - INFO - Recibido: 5
2024-06-07 18:55:13,520 - __main__ - INFO - Se ha tomado una foto
2024-06-07 18:55:13,545 - __main__ - INFO - se ha tomado una foto
2024-06-07 18:55:16,475 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-07 18:55:16,477 - websockets.server - INFO - connection closed
2024-06-07 18:55:23,809 - websockets.server - INFO - connection open
2024-06-07 18:55:23,813 - __main__ - INFO - Recibido: 8
2024-06-07 18:55:23,813 - __main__ - INFO - Tomando foto a una pizarra
2024-06-07 18:55:23,841 - __main__ - INFO - Se ha tomado una foto a una pizarra
2024-06-07 18:56:11,565 - websockets.server - INFO - connection closed
2024-06-07 18:56:11,634 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-14' coro=<WebSocketServerProtocol.handler() done, defined at /usr/lib/python3/dist-packages/websockets/legacy/server.py:153> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/opt/scripts/socket_cliente.py", line 125, in <module>
    asyncio.run(main(args.clase))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 107, in handle_client
    captura_pizarra(f"/datos/{clase}")
  File "/opt/scripts/take_pizarra.py", line 35, in captura_pizarra
    while time.time() - start_time < 3:
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
2024-06-08 10:46:43,833 - websockets.server - INFO - server listening on [::1]:8766
2024-06-08 10:46:43,835 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-08 10:46:43,835 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class SRI1
2024-06-08 10:46:59,375 - websockets.server - INFO - connection open
2024-06-08 10:46:59,377 - __main__ - INFO - Recibido: 6
2024-06-08 10:46:59,377 - __main__ - INFO - Iniciando la clase
2024-06-08 10:46:59,407 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:46:59,414 - websockets.server - INFO - connection closed
2024-06-08 10:47:04,757 - websockets.server - INFO - connection open
2024-06-08 10:47:04,758 - __main__ - INFO - Recibido: 1
2024-06-08 10:47:04,758 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-08 10:47:04,773 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-08 10:47:05,777 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:47:05,779 - websockets.server - INFO - connection closed
2024-06-08 10:47:18,558 - websockets.server - INFO - connection open
2024-06-08 10:47:18,560 - __main__ - INFO - Recibido: 5
2024-06-08 10:47:18,560 - __main__ - INFO - Se ha tomado una foto
2024-06-08 10:47:18,575 - __main__ - INFO - se ha tomado una foto
2024-06-08 10:47:21,709 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:47:21,710 - websockets.server - INFO - connection closed
2024-06-08 10:47:55,266 - websockets.server - INFO - connection open
2024-06-08 10:47:55,267 - __main__ - INFO - Recibido: 6
2024-06-08 10:47:55,267 - __main__ - INFO - Iniciando la clase
2024-06-08 10:47:55,286 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:47:55,288 - websockets.server - INFO - connection closed
2024-06-08 10:48:56,373 - websockets.server - INFO - connection open
2024-06-08 10:48:56,376 - __main__ - INFO - Recibido: 3
2024-06-08 10:48:56,377 - __main__ - INFO - Se ha iniciado la grabacion
2024-06-08 10:50:35,832 - __main__ - INFO - Ejecutando script para empezar grabación
2024-06-08 10:50:35,835 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1197, in drain
    await self._drain()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 334, in _drain
    raise exc
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 968, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1170, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/framing.py", line 69, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 717, in readexactly
    raise self._exception
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 1057, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-06-08 10:50:35,842 - websockets.server - INFO - connection closed
2024-06-08 10:50:35,843 - websockets.server - INFO - connection open
2024-06-08 10:50:35,844 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 968, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1170, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/framing.py", line 69, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 726, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-06-08 10:50:35,846 - websockets.server - INFO - connection closed
2024-06-08 10:53:57,989 - websockets.server - INFO - server listening on [::1]:8766
2024-06-08 10:53:57,989 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-08 10:53:57,989 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class SRI1
2024-06-08 10:54:18,499 - websockets.server - INFO - connection open
2024-06-08 10:54:18,501 - __main__ - INFO - Recibido: 6
2024-06-08 10:54:18,501 - __main__ - INFO - Iniciando la clase
2024-06-08 10:54:18,524 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:54:18,527 - websockets.server - INFO - connection closed
2024-06-08 10:54:30,788 - websockets.server - INFO - connection open
2024-06-08 10:54:30,789 - __main__ - INFO - Recibido: 5
2024-06-08 10:54:30,790 - __main__ - INFO - Se ha tomado una foto
2024-06-08 10:54:30,805 - __main__ - INFO - se ha tomado una foto
2024-06-08 10:54:33,729 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:54:33,731 - websockets.server - INFO - connection closed
2024-06-08 10:54:51,801 - websockets.server - INFO - connection open
2024-06-08 10:54:51,803 - __main__ - INFO - Recibido: 3
2024-06-08 10:54:51,803 - __main__ - INFO - Se ha iniciado la grabacion
2024-06-08 10:54:51,820 - __main__ - INFO - Ejecutando script para empezar grabación
2024-06-08 10:54:51,827 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:54:51,828 - websockets.server - INFO - connection closed
2024-06-08 10:55:04,994 - websockets.server - INFO - connection open
2024-06-08 10:55:04,996 - __main__ - INFO - Recibido: 4
2024-06-08 10:55:04,996 - __main__ - INFO - Se ha detenido la grabacion
2024-06-08 10:55:05,018 - __main__ - INFO - Deteniendo la grabación
2024-06-08 10:55:05,025 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:55:05,027 - websockets.server - INFO - connection closed
2024-06-08 10:56:51,236 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-08 10:56:51,237 - websockets.server - INFO - server listening on [::1]:8766
2024-06-08 10:56:51,237 - __main__ - INFO - Server started and listening on ws://localhost:8766 for class SRI2
2024-06-08 10:56:55,003 - websockets.server - INFO - connection open
2024-06-08 10:56:55,005 - __main__ - INFO - Recibido: 6
2024-06-08 10:56:55,005 - __main__ - INFO - Iniciando la clase
2024-06-08 10:56:55,029 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:56:55,033 - websockets.server - INFO - connection closed
2024-06-08 10:57:00,704 - websockets.server - INFO - connection open
2024-06-08 10:57:00,706 - __main__ - INFO - Recibido: 5
2024-06-08 10:57:00,706 - __main__ - INFO - Se ha tomado una foto
2024-06-08 10:57:00,720 - __main__ - INFO - se ha tomado una foto
2024-06-08 10:57:03,638 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:57:03,640 - websockets.server - INFO - connection closed
2024-06-08 10:57:10,006 - websockets.server - INFO - connection open
2024-06-08 10:57:10,009 - __main__ - INFO - Recibido: 3
2024-06-08 10:57:10,009 - __main__ - INFO - Se ha iniciado la grabacion
2024-06-08 10:57:10,036 - __main__ - INFO - Ejecutando script para empezar grabación
2024-06-08 10:57:10,043 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:57:10,045 - websockets.server - INFO - connection closed
2024-06-08 10:57:17,908 - websockets.server - INFO - connection open
2024-06-08 10:57:17,909 - __main__ - INFO - Recibido: 4
2024-06-08 10:57:17,910 - __main__ - INFO - Se ha detenido la grabacion
2024-06-08 10:57:17,931 - __main__ - INFO - Deteniendo la grabación
2024-06-08 10:57:17,940 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 26, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-08 10:57:17,942 - websockets.server - INFO - connection closed
2024-06-08 11:22:54,550 - websockets.server - INFO - connection open
2024-06-08 11:22:54,551 - __main__ - INFO - Recibido: 7
2024-06-08 11:22:54,552 - __main__ - INFO - Termina la clase
2024-06-08 11:22:54,566 - __main__ - INFO - Finalizando la clase
2024-06-08 11:22:54,566 - websockets.server - INFO - connection closed
2024-06-08 11:22:54,599 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-24' coro=<WebSocketServerProtocol.handler() done, defined at /usr/lib/python3/dist-packages/websockets/legacy/server.py:153> exception=SystemExit(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 99, in handle_client
    quit()
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: None
